apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 0.10.0
    helm:
      values: |
        alloy:
          configMap:
            create: true
            content: |
              logging {
                level = "info"
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
