apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaafar-harabi/local-gitops-observability-lab.git
    targetRevision: main
    path: charts/otel-collector
  destination:
    server: https://kubernetes.default.svc
    namespace: otel
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
